name = input("Enter your full name: ")
# result = len(name)
# result = name.capitalize()
# result = name.title()
# result = name.upper()
# result = name.lower()
# result = name.strip()
# result = name.find("d")
# print(result)